app1/urls.py
from app1.views import *
from django.urls import path

app_name='namita'
urlpatterns=[
    path('dad/',dad,name='dad'),
]

app2/urls.py
from app2.views import *
from django.urls import path

app_name='panchu'
urlpatterns=[
    path('mom/',mom,name='mom'),
]

urlnavigation1/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2


urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def dad(request):
    return render(request,'dad.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def mom(request):
    return render(request,'mom.html')

templates/dad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is for you my love</h1>
        <h1>i dont want whole worlds attention,</h1>
        <h1>your attention meansthe world to me</h1>
        <a href="{% url 'panchu:mom' %}"><h2>resoponse of mom</h2></a>
    </center>
    
</body>
</html>

templates/mom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            you are not just my man
        </h1>
        <h1>you are my home,my rest,my heart,my safepalce</h1>
       <a href="{% url 'namita:dad' %}"> <h1>go to dad respose</h1></a>
    </center>
    
</body>
</html>